### ISSUE TITLE
Error in dimensions with regards to conv2d

### ISSUE THREAD

**Issue by AetherPrior** [varun-parthasarathy/eye_tracker#2]
running train_eye_tracker.py gave this result. Any reason?
```
Traceback (most recent call last):
  File "train_eye_tracker.py", line 95, in <module>
    trainModel()
  File "train_eye_tracker.py", line 88, in trainModel
    model.fit(X, Y, validation_split=0.10, epochs=25, batch_size=64, shuffle=True)
  File "/home/l12-o-0-554/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/home/l12-o-0-554/.local/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/home/l12-o-0-554/.local/lib/python3.7/site-packages/keras/engine/training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (0, 1)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "train_eye_tracker.py", line 95, in <module>
    trainModel()
  File "train_eye_tracker.py", line 88, in trainModel
    model.fit(X, Y, validation_split=0.10, epochs=25, batch_size=64, shuffle=True)
  File "/home/l12-o-0-554/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/home/l12-o-0-554/.local/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/home/l12-o-0-554/.local/lib/python3.7/site-packages/keras/engine/training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (0, 1)
```

Running generate_training_data.py gave another error:
```
QObject::moveToThread: Current thread (0x2e932b0) is not the object's thread (0x7b38010).
Cannot move to target thread (0x2e932b0)

Segmentation fault (core dumped)
```

Is there a good way to set this all up?

**Comment by AetherPrior** [comment]
I figured it out. Turns out opencv has a problem with kubuntu / KDE, if Qt versions between the opencv library and the OS are different. I had to build it so that its GUI used GTK instead of Qt.

**Comment by AetherPrior** [comment]
Also fixed my Python3 error, it was caused by pip3 being linked to pip3.7 and uninstall happening on dist-packages when the library was improperly installed in site-packages
